camunda-community-hub/zeebe-client-csharp

Client/Impl/Worker/JobWorker.cs
Log RpcException with log level 'Debug' when status code is DeadlineExceeded or Cancelled
closes #86
=> feat(client): Log RpcException with log level 'Debug' 

Client.UnitTests/ZeebeClientTest.cs, Client/ZeebeClient.cs
=> fix(client): Checks if the gateway is already closed before trying to shutdown the gateway

Client.UnitTests/GatewayTestService.cs, Client.UnitTests/RequestMetadataTest.cs, Client/ZeebeClient.cs
Sends the client type and version as user-agent header.
closes #110
=> chore(client): use user-agent to send client version

Client.IntegrationTests/JobWorkerTest.cs, Client.UnitTests/RequestMetadataTest.cs, Client/Api/Builder/IZeebeClientBuilder.cs, Client/Impl/Builder/ZeebeClientBuilder.cs, Client/ZeebeClient.cs
Adds an optional parameter to set the keepAlive interval.
Use a default configuration of 30 seconds to send periodically keepAlive pings, during an requests
Useful for workflow instance with result creation.
closes #91
=> Add keepAlive ping

Client.IntegrationTests/JobWorkerTest.cs, Client.IntegrationTests/OldVersionBrokerTopologyTest.cs, Client.IntegrationTests/WorkflowInstanceTest.cs, Client.IntegrationTests/WorkflowTest.cs, Client.IntegrationTests/ZeebeIntegrationTestHelper.cs, Client/Api/Responses/ITopology.cs, Client/Impl/Responses/Topology.cs, Client/Impl/proto/Gateway.cs, generate-grpc/gen-grpc.sh
*  Use latest versions of grpc and zeebe.
*  Resolve script dir to be independent of execution dir.
* Update proto file to 0.23.0
* Add GatewayVersion to Topology.
* As fallback string 'lower then 0.23' is used
* Add IT test, which test lower version of gateway and broker
closes #112
=> Add gateway version to topology

Client/Impl/Worker/JobWorker.cs
Previous we wait endless on the handler thread until we get a next job, the problem was that we not check in between whether the worker was already closed/disposed. We now wait the poll interval and check whether we should stop the handler thread.
Furthermore we dispose also the cancelationTokenSource after pollInterval multiplied by 2 to make sure the other threads are closed before.
closes #122
=> fix(client): close handler thread correctly

Client/Impl/Commands/ActivateJobsCommand.cs, Client/Impl/Worker/JobWorker.cs, Client/ZeebeClient.cs
=> fix(client): Add delay within catch block in JobWorker.PollJobs to avoid server hogging.

Client.UnitTests/CamundaCloudTokenProviderTest.cs, Client/Impl/Builder/CamundaCloudTokenProvider.cs
> Creates the HttpClient in CamundaCloudTokenProvider constructor. Added CamundaCloudTokenProvider.SetHttpMessageHandler method to set the HttpMessageHandler for testing which will create a new HttpClient.
> 
> closes #218
closes https://github.com/zeebe-io/zeebe-client-csharp/pull/222
=> Prevent disposing of the HttpMessageHandler

README.md
Added new Shields.io badges indicating this is a community supported extension and denoted its Stable [lifecycle status](https://github.com/camunda-community-hub/community/blob/main/extension-lifecycle.md)
=> Added new Shields.io badges

.github/workflows/aspnetcore.yml
Dependabot has problems on accessing secrets, for now we try without it.
Let's see how it works
=> Remove docker login

Client.UnitTests/CamundaCloudTokenProviderTest.cs, Client/Impl/Builder/CamundaCloudTokenProvider.cs
* add audience to stored credentials
* add missing tests
closes https://github.com/camunda-community-hub/zeebe-client-csharp/issues/146
=> Fix multiple cluster credentials handling

.github/workflows/aspnetcore.yml, Client.Cloud.Example/Client.Cloud.Example.csproj, Client.Examples/Client.Examples.csproj, Client.IntegrationTests/Client.IntegrationTests.csproj, Client.UnitTests/Client.UnitTests.csproj
=> #277 - Migrate to .Net Core 3.1

Client.IntegrationTests/Client.IntegrationTests.csproj, Client.IntegrationTests/ZeebeIntegrationTestHelper.cs
Updates the Testcontainers for .NET NuGet dependency to its latest release. Assigns a random host port to the service running inside a container (best practice). Resolve the hostname instead of a fixed value (endpoint my differ due to the Docker environment, Testcontainers resolves the right endpoint).
I noticed you are using an outdated version. The version is probably not compatible with Docker Desktop, etc. anymore. To leverage Testcontainesr into your test environment, I recommend the latest release.
If you have issues setting up Testcontinaers, let me know. I am happy to help. While I was browsing through the source code I noticed some parts that can be improved. I addressed some of them immediately.
\-
=> feat: Update Testcontainers for .NET

Client.UnitTests/FailJobTest.cs, Client/Api/Commands/IFailJobCommandStep1.cs, Client/Impl/Commands/FailJobCommand.cs
=> feat: allowed to set retryBackOff parameter of FailJobCommand

.github/workflows/aspnetcore.yml, .github/workflows/release.yaml, Client.Cloud.Example/Client.Cloud.Example.csproj, Client.Examples/Client.Examples.csproj, Client.IntegrationTests/Client.IntegrationTests.csproj, Client.UnitTests/Client.UnitTests.csproj, Client/Client.csproj, global.json
relates to #517 
relates to #348 
relates to https://github.com/camunda-community-hub/zeebe-client-csharp/issues/277
First part of migrating to grpc-dotnet is to migrate to the latest .net version. Migrating to .net 7.0 since that is the latest version, which is still supported all others are already eol https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core.
=> Migrate to .net 7.0

Client/Client.csproj
Grpc.Core is deprecated and should no longer be used https://grpc.io/blog/grpc-csharp-future/
closes https://github.com/camunda-community-hub/zeebe-client-csharp/issues/348
closes https://github.com/camunda-community-hub/zeebe-client-csharp/issues/194
=> Migrate to grpc.net.client

Client.IntegrationTests/Client.IntegrationTests.csproj, Client.IntegrationTests/EvaluateDecisionTest.cs, Client.IntegrationTests/Resources/dinnerDecisions.dmn, Client.UnitTests/EvaluateDecisionTest.cs, Client.UnitTests/GatewayTestService.cs, Client.UnitTests/TestDataProvider.cs, Client/Api/Commands/IEvaluateDecisionCommandStep1.cs, Client/Api/Responses/IEvaluateDecisionResponse.cs, Client/Api/Responses/IEvaluatedDecision.cs, Client/Api/Responses/IEvaluatedDecisionInput.cs, Client/Api/Responses/IEvaluatedDecisionOutput.cs, Client/Api/Responses/IMatchedDecisionRule.cs, Client/Client.csproj, Client/IZeebeClient.cs, Client/Impl/Commands/EvaluateDecisionCommand.cs, Client/Impl/Responses/EvaluatedDecision.cs, Client/Impl/Responses/EvaluatedDecisionInput.cs, Client/Impl/Responses/EvaluatedDecisionOutput.cs, Client/Impl/Responses/EvaluatedDecisionResponse.cs, Client/Impl/Responses/MatchedDecisionRule.cs, Client/ZeebeClient.cs
Allows to use the evaluate decision feature from Zeebe which was added with 8.2
=> Add evaluate decision feature

Client.UnitTests/PublishMessageTest.cs, Client.UnitTests/ThrowErrorTest.cs, Client/Api/Commands/IPublishMessageCommandStep1.cs, Client/Api/Commands/IThrowErrorCommandStep1.cs, Client/Impl/Commands/ThrowErrorCommand.cs
Adds missing variables to ThrowError
closes #568
=> Add vars to ThrowError

Client.UnitTests/DeploymentTest.cs, Client/Api/Commands/IDeployResourceCommandStep1.cs, Client/Api/Commands/ITenantIdCommandStep.cs, Client/Impl/Commands/DeployResourceCommand.cs
Updates `DeployResourceCommand` to support TenantId.
This is one of two interfaces I would like to introduce for TenantId.
This begins the work to update the various builders to support multi-tenancy in [591](https://github.com/camunda-community-hub/zeebe-client-csharp/issues/591)
Splitting out into smaller PR's as requested by author.
=> Updated DeployResourceCommand to support TenantId.

Client.UnitTests/Client.UnitTests.csproj, Client.UnitTests/GatewayTestService.cs, Client.UnitTests/ModifyProcessInstanceTest.cs, Client/Api/Commands/IModifyProcessInstanceCommandStep1.cs, Client/Api/Responses/IModifyProcessInstanceResponse.cs, Client/IZeebeClient.cs, Client/Impl/Commands/ModifyProcessInstanceCommand.cs, Client/Impl/Responses/ModifyProcessInstanceResponse.cs, Client/ZeebeClient.cs
_Based on https://github.com/camunda-community-hub/zeebe-client-csharp/pull/622_
I took the state from https://github.com/camunda-community-hub/zeebe-client-csharp/pull/622 and reworked it a bit to align with the Java client implementation, so examples can be reused and we have the same experience in the clients. See related interface in Java client https://github.com/camunda/zeebe/blob/main/clients/java/src/main/java/io/camunda/zeebe/client/api/command/ModifyProcessInstanceCommandStep1.java
closes #622
=> Add ModifyProcessInstance to client

Client.UnitTests/ActivateJobTest.cs, Client/Api/Commands/IActivateJobsCommandStep1.cs, Client/Api/Commands/ITenantIdsCommandStep.cs, Client/Impl/Commands/ActivateJobsCommand.cs
Updates `ActivateJobsCommand` to support TenantIds.
This is the second interface I would like to introduce for TenantIds.
This continues the work to update the various builders to support multi-tenancy in [591](https://github.com/camunda-community-hub/zeebe-client-csharp/issues/591)
=> ActivateJobsCommand updated to set tenantIds.

Client/Client.csproj
=> #669 externalise dependency

Client.UnitTests/DeploymentTest.cs, Client.UnitTests/Resources/demo-form.form, Client/Api/Responses/IDeployResourceResponse.cs, Client/Api/Responses/IFormMetadata.cs, Client/Impl/Responses/DeployResourceResponse.cs, Client/Impl/Responses/FormMetadata.cs
This PR adds support for form deployment response and closes #648
I've tried to keep the implementation as similar as possible to the existing deployment response types. Let me know if there is anything else I should include in this PR.
=> fix(deployment): Added support for form deployment response

Client.UnitTests/CreateProcessInstanceTest.cs, Client.UnitTests/CreateProcessInstanceWithResultTest.cs, Client.UnitTests/JobWorkerTest.cs, Client/Api/Commands/ICreateProcessInstanceCommandStep1.cs, Client/Api/Responses/IJob.cs, Client/Api/Worker/IJobWorkerBuilderStep1.cs, Client/Impl/Commands/CreateProcessInstanceCommand.cs, Client/Impl/Responses/ActivatedJob.cs, Client/Impl/Worker/JobWorkerBuilder.cs
This PR adds tenant ID to
- create process command
- job worker builder
closes parts of #591
=> Feature/add tenant id to job / create process command

Client.UnitTests/GatewayTestService.cs, Client.UnitTests/TestDataProvider.cs, Client.UnitTests/UpdateJobTimeoutTest.cs, Client/Api/Commands/IUpdateJobTimeoutCommandSteps.cs, Client/Api/Responses/IUpdateJobTimeoutResponse.cs, Client/IZeebeClient.cs, Client/Impl/Commands/UpdateJobTimeoutCommand.cs, Client/Impl/Responses/UpdateJobTimeoutResponse.cs, Client/ZeebeClient.cs
Added a command for updating the timeout of a job
closes #681
=> Implementation of UpdateJobTimeoutCommand

Client.UnitTests/Client.UnitTests.csproj, Client/Client.csproj, Client/ZeebeClient.cs
This 1st PR only moves the Grpc.Core dependency to tests. The client is clean after that. Note that Grpc.Core.Api is still part of the https://github.com/grpc/grpc-dotnet project.
=> refactor: get rid of Grpc.core dependency into ZeebeClient

Client/Api/Responses/IPublishMessageResponse.cs, Client/Api/Responses/IResolveIncidentResponse.cs, Client/Api/Responses/ISetVariablesResponse.cs, Client/Api/Responses/IThrowErrorResponse.cs, Client/Api/Responses/ITopology.cs, Client/Api/Responses/IUpdateJobTimeoutResponse.cs, Client/Api/Responses/IUpdateRetriesResponse.cs, Client/Api/Responses/PartitionBrokerRole.cs, Client/Api/Worker/IJobClient.cs, Client/Api/Worker/IJobWorker.cs, Client/Api/Worker/IJobWorkerBuilderStep1.cs, Client/ZeebeClient.cs
=> Reformat Client/API: use file-scope namespace and primary constructor

Client/Impl/Builder/CamundaCloudClientBuilder.cs, Client/Impl/Builder/CamundaCloudTokenProvider.cs, Client/Impl/Commands/ActivateJobsCommand.cs, Client/Impl/Commands/CancelProcessInstanceCommand.cs, Client/Impl/Commands/CompleteJobCommand.cs, Client/Impl/Commands/CreateProcessInstanceCommand.cs, Client/Impl/Commands/CreateProcessInstanceCommandWithResult.cs, Client/Impl/Commands/DeployResourceCommand.cs, Client/Impl/Commands/EvaluateDecisionCommand.cs, Client/Impl/Commands/FailJobCommand.cs, Client/Impl/Commands/JobActivator.cs, Client/Impl/Commands/ModifyProcessInstanceCommand.cs, Client/Impl/Commands/PublishMessageCommand.cs, Client/Impl/Commands/ResolveIncidentCommand.cs, Client/Impl/Commands/SetVariablesCommand.cs, Client/Impl/Commands/ThrowErrorCommand.cs, Client/Impl/Commands/TimeSpanExtensions.cs, Client/Impl/Commands/TopologyRequestCommand.cs, Client/Impl/Commands/UpdateJobTimeoutCommand.cs, Client/Impl/Commands/UpdateRetriesCommand.cs
=> style: use file-scope namespace and primary constructor

Client.UnitTests/CreateProcessInstanceWithResultTest.cs, Client/Api/Commands/ICreateProcessInstanceCommandStep1.cs, Client/Impl/Commands/CreateProcessInstanceCommand.cs
closes https://github.com/camunda-community-hub/zeebe-client-csharp/pull/750
closes https://github.com/camunda-community-hub/zeebe-client-csharp/issues/581
Copy of #750 - with smaller adjustments
Contribution by @daghsentinel
=> Start process at Element
