Client.UnitTests/JobWorkerTest.cs
Client/Api/Responses/IJob.cs
Client/Impl/Responses/ActivatedJob.cs

feat(client): expose CustomHeaders on Activated Job

---

Client.UnitTests/ActivateJobTest.cs
Client.UnitTests/BaseZeebeTest.cs
Client.UnitTests/CancelWorkflowInstanceTest.cs
Client.UnitTests/CompleteJobTest.cs
Client.UnitTests/CreateWorkflowInstanceTest.cs
Client.UnitTests/CreateWorkflowInstanceWithResultTest.cs
Client.UnitTests/DeploymentTest.cs
Client.UnitTests/FailJobTest.cs
Client.UnitTests/GatewayTestService.cs
Client.UnitTests/JobWorkerTest.cs
Client.UnitTests/PublishMessageTest.cs
Client.UnitTests/RequestTopologyTest.cs
Client.UnitTests/ResolveIncidentTest.cs
Client.UnitTests/UpdatePayloadTest.cs
Client.UnitTests/UpdateRetriesTest.cs

Fixes flaky tests with concurrent request map
Still not ideal but better then before

Fix flaky tests

---

Client.Examples/Program.cs
Client.Examples/Resources/demo-process.bpmn

Turn abstract example into an order process

---

Client.UnitTests/CamundaCloudTokenProviderTest.cs
Client/Builder/CamundaCloudTokenProvider.cs

chore(client): add disponse on token provider

---

Client/Impl/Worker/JobWorker.cs

* TaskFactory.StartNew was replaced with Task.Run, since the first one should not be used with
async methods
* await results of sended requests and log errors
closes #41
closes #40

fix(client): fix job worker task handling

---

Client.UnitTests/CreateWorkflowInstanceWithResultTest.cs
Client/Impl/Commands/CreateWorkflowInstanceCommandWithResult.cs

Request timeout was not set on the gRPC message. We now have a default request timeout, which we set when send(Timeout = null). The deadline between client and gateway is always larger now then the timeout between gateway and broker.
closes #138

fix(client): set request timeout correctly

---

Client.UnitTests/JobWorkerTest.cs
Client/Impl/Worker/JobWorker.cs
Client/Impl/Worker/JobWorkerBuilder.cs

Refactor job worker after last rewrite and bring job activation threshold back.

Refactor job worker

---

Client.IntegrationTests/BrokerTopologyTest.cs
Client.IntegrationTests/ZeebeIntegrationTestHelper.cs
Client/Impl/proto/Gateway.cs
generate-grpc/gen-grpc.sh

* generate new protofile (for 0.26.1)
* migrate it tests to 0.26.1

Migrate to 0.26.1

---

.github/workflows/aspnetcore.yml
Client.IntegrationTests/ZeebeIntegrationTestHelper.cs
Client.UnitTests/DeploymentTest.cs
Client/Impl/Commands/DeployProcessCommand.cs
Client/Impl/proto/Gateway.cs
Client/Impl/proto/GatewayGrpc.cs
generate-grpc/gen-grpc.sh

* Regenerate proto file
* remove ResourceType usage

Update to release 1.0.0-alpha7

---

Client.UnitTests/CompleteJobTest.cs
Client/Api/Commands/ICompleteJobCommandStep1.cs
Client/Impl/Commands/CompleteJobCommand.cs
Client/ZeebeClient.cs

feat: add SendWithRetry to CompleteJobCommand

---

Client.UnitTests/TestDataProvider.cs
Client/Api/Commands/IActivateJobsCommandStep1.cs

closes https://github.com/camunda-community-hub/zeebe-client-csharp/issues/173

feat: impl SendWithRetry for JobActivation

---

Client/Impl/Worker/JobWorker.cs

In the worker a volatile field was increment and decrement which is unfortunately not thread safe https://stackoverflow.com/questions/154551/volatile-vs-interlocked-vs-lock
In order to be thread safe the Interlocked class is used, alternatively locks can be used. The volatile mark is removed from the field, since this is not supported by Interlocked. To be able to read the value Thread.volatileRead is used https://stackoverflow.com/questions/24808291/reading-an-int-thats-updated-by-interlocked-on-other-threads

fix: use Interlocked to be thread safe

---

Client.UnitTests/TestDataProvider.cs
Client/Api/Commands/IDeployProcessCommandStep1.cs
Client/Api/Commands/IFailJobCommandStep1.cs
Client/Impl/Commands/CreateProcessInstanceCommandWithResult.cs
Client/Impl/Commands/DeployProcessCommand.cs
Client/Impl/Commands/FailJobCommand.cs
Client/ZeebeClient.cs

Replaces PR by @askalik and fix some certain things.
closes #339 (PR)
closes #178

Askalik feature fail job command with retries

---

Client/Impl/Worker/JobWorker.cs

Fix: High CPU consumption when the connection is lost.

---

Client.UnitTests/ZeebeClientTest.cs
Client/ZeebeClient.cs

Return max if exceeding max wait time

---

Client/Impl/proto/Gateway.cs
Client/Impl/proto/GatewayGrpc.cs
generate-grpc/gen-grpc.sh

Upgrade generated grpc protocol to 8.2.8

Gen to Zeebe grpc protocol v8.2.8

---

.github/workflows/ci.yml
.github/workflows/pull-request-ci.yaml
.github/workflows/release.yaml
Client/Client.csproj
global.json

* change global.json to .net 8.0.100
* change ci to use .net 8
closes https://github.com/camunda-community-hub/zeebe-client-csharp/issues/595
closes https://github.com/camunda-community-hub/zeebe-client-csharp/issues/582

Migrate project to .net 8.0

---

CONTRIBUTING.md
Client.UnitTests/FailJobTest.cs
Client/Api/Commands/IFailJobCommandStep1.cs
Client/Impl/Commands/FailJobCommand.cs

Issue 677 Add Variables property to FailJobCommand

---

Client/IZeebeClient.cs
Client/Impl/Misc/AccessToken.cs
Client/Impl/Misc/PersistedAccessTokenCache.cs
Client/Impl/Misc/TransientGrpcErrorRetryStrategy.cs
Client/Impl/Worker/JobClientWrapper.cs
Client/Impl/Worker/JobWorker.cs
Client/Impl/Worker/JobWorkerBuilder.cs
Client/Impl/proto/ClosedGatewayClient.cs
Client/ServiceCollectionExtensions.cs

style: use file-scope namespace and primary constructor

---

Client.UnitTests/BroadcastSignalTest.cs
Client.UnitTests/GatewayTestService.cs
Client/Api/Commands/IBroadcastSignalCommandStep1.cs
Client/Api/Responses/IBroadcastSignalResponse.cs
Client/IZeebeClient.cs
Client/Impl/Commands/BroadcastSignalCommand.cs
Client/Impl/Responses/BroadcastSignalResponse.cs
Client/ZeebeClient.cs

Added BroadcastSignalCommand implementation
Added unit tests
Done by following PublishMessageCommand implementation
closes #752

feat: add BroadcastSignalCommand

---

Client.UnitTests/EvaluateDecisionTest.cs
Client/Api/Commands/IEvaluateDecisionCommandStep1.cs
Client/Impl/Commands/EvaluateDecisionCommand.cs

feat: Add tenantId support to EvaluateDecisionCommand.

---

Client.UnitTests/DeleteResourceTest.cs
Client.UnitTests/GatewayTestService.cs
Client/Api/Commands/IDeleteResourceCommandStep1.cs
Client/Api/Responses/IDeleteResourceResponse.cs
Client/IZeebeClient.cs
Client/Impl/Commands/DeleteResourceCommand.cs
Client/Impl/Responses/DeleteResourceResponse.cs
Client/ZeebeClient.cs

feat: add command to zeebeclient and added unit tests
feat: added new DeleteResource handler to GatewayTestService.

feat: implement delete resource
